<?php $WEBSITE_NAME = "Eposting";
$WEBSITE_PROFILE_URL = "";
$WEBSITE_WEBSITE = "";
$WEBSITE_DESCRIPTION = "";
$WEBSITE_EMAIL = "";
$WEBSITE_HTACCESS = False;

// UTTERANCES (Comment section)
$WEBSITE_UTTERANCES = False;
$WEBSITE_UTTERANCES_SCRIPT = ''; ?>
